# Generated by Django 4.2.1 on 2023-05-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.TextField(default='Wallet1', max_length=128),
            preserve_default=False,
        ),
    ]
